### PR TITLE
Fix for bug in inactive set calculation.

### PR DESCRIPTION
**Pull request by jhale**

### CODE REVIEW

**Comment by jhale** [comment]
@a-latyshev Can you check this corresponds with what we discussed earlier?

**Comment by a-latyshev** [comment]
These changes seem to be in line with our last meeting. I cannot add anything from my side at the moment. :)

**Comment by a-latyshev** [comment]
@jhale I think you can put
```python
    # Construct inactive set on displacement.
    u_inactive_set = np.arange(
        0, V_u.dofmap.index_map_bs * V_u.dofmap.index_map.size_local, dtype=np.int32
    )
    u_restrict = np.setdiff1d(u_inactive_set, bc_dofs_u_all)
```
 outside of the main loop for a better performance as well as the assembling of the matrix `B`, I suppose.
```python
    B.zeroEntries()
    fem.petsc.assemble_matrix_block(B, B_form)
    B.assemble()
```

**Comment by jhale** [comment]
Thanks - I will do this in another branch, and also the fixes for `snes.solve`.

**Pull request merged**
